### ISSUE TITLE
Duolingo Image is blurred

### ISSUE THREAD

**Issue by CennoxX** [pacjo/SmartspacerPlugins#16] opened 2024-09-21 11:48 UTC
For a few days now, every image in the Duolingo Smartspacer plugin has been blurred. 
![Screenshot_20240921-134525](https://github.com/user-attachments/assets/47069b10-8a51-4c69-aa9d-3b13e905f7d5)

**Comment by pacjo** [comment] 2024-09-21 12:58
That's an interesting failure. Can't reproduce.

Do you have the latest version of duolingo installed? I just updated and we'll see if it shows up on mine.

Also does this show up before or after finishing a lesson?

**Comment by CennoxX** [comment] 2024-09-21 19:23
It shows when before and after finishing a lesson. I have the latest version of duolingo 5.169.3.

**Comment by pacjo** [comment] 2024-09-22 17:20
Ok, I set widget size to 2x1 tiles (not sure what exactly, since it's a smartspacer sdk utility function) and it still works. I'm using moded apk, so latest for me is 5.168.3.

Anyway, here's a version with the change. Does it make a difference?
[app-duolingo-release.zip](https://github.com/user-attachments/files/17090562/app-duolingo-release.zip)

**Comment by CennoxX** [comment] 2024-09-22 18:23
No this doesn't make a difference 🫤

**Comment by pacjo** [comment] 2024-09-22 19:44
That's... not good. But I can reproduce it on both lawnchair and pixel launcher, if I install latest from play store.

That's definitely a release blocker for 1.5.

**Comment by sarojpanda44** [comment] 2024-09-24 09:41
Same issue with Lawnchair 14 play store version

**Comment by pacjo** [comment] 2024-09-24 11:28
> Same issue with Lawnchair 14 play store version

I'm sorry you're the person who triggered this ~~small~~ rant, but it was a long time comming.

Commenting *same* on a know issue isn't helpful. If you want to receive updates there's a *subscribe* button in the sidebar or at the bottom of the page. Comments like this aren't helpful. I appreciate that this one is a bit more then just *same* and has some useful information, but my point stands.

Maybe this project isn't the best example of this since the most active issue in this repo had 3 or 4 people in it. But take a look at larger projects where they have known open issues and every once in a while someone comes to comment the same thing.

I know about this. There are my responses on this issue and I confirmed I can reproduce it. Sometime in the future a fix will be released, but until then this stays open.

I work on projects in my free time, whenever I feel like it. I'm not paid, I don't put advertisements. I don't even have a *support the creator* button anywhere apart from the about app page which most probably will never visit.

I like programming the same way I like sleep. There's a point at which it becomes too much.

So please. If you haven't got much to add. If there's already an open ticket for the problem you're describing. And if there's any option to react on the issue (like you did, which I appreciate), to mark *I experience this too, but I don't have anything to add* checkbox... Prefer that to a comment.

Maybe I just got email about your comment in the wrong moment. Considering the circumstances, there's a good chance my rant isn't needed. But once again consider the same in the context of a large project where not 3 but 30 people would comment the same thing. That gets annoying quickly.

**Comment by pacjo** [comment] 2024-09-25 12:02
[app-duolingo-release.zip](https://github.com/user-attachments/files/17130417/app-duolingo-release.zip)

Ok, I changed *something*, removed some code and now it works (as a `debug` on pixel launcher (latest duolingo from play store) and as `release` on lawnchair (both latest and my, slightly older, version)).

It should work out of the box, if not try to remove and add back the target.

**Comment by sarojpanda44** [comment] 2024-09-25 12:48
It works with the updated plugin. Thanks for your time and checking it for a fix.

![Screenshot_20240925-144715](https://github.com/user-attachments/assets/9e45dedf-628e-451a-8851-12a46902f994)

**Comment by pacjo** [comment] 2024-09-25 12:53
Awesome. Closing.

**Closed by pacjo** 2024-09-25 12:53 UTC
